### ISSUE TITLE
Issue: Bag dupe bug

### ISSUE THREAD

**Issue by tomatheb** [tattyseal/IssueTracker#10]
```
When using a bag, ordinarily its own item is unmovable. When you use number keys to move something into the location of the bag, it becomes movable and when closed any changes to its inventory are lost but the items remain in the inventory. 
```

What's happening?: Bag gets displaced and protections are lifted, resulting in dupe glitch (and void glitch). (Incidentally, protections remain on item moved into slot.)
What's expected to happen?: When using number key to move item to slot of bag, nothing should happen
Replication Steps: Open bag from compact storage, put something in it. Reopen and then use number keys to move item into same hot bar slot as opened bag. Close bag and reopen. It will still have moved items inside.

Mod Version: 2.0.0.12
Minecraft Version: 1.7.10
Forge Version: -unknown-
Modpack (if applicable): Agrarian Skies 1.1.8 with Fastcraft 1.21
Log URL: https://gist.github.com/tomatheb/0a2892949cd94f15e5c4

`Edited by tattyseal to follow issue guidelines as it is an old issue`

**Comment by elifoster** [comment]
@tattyseal This isn't really relevant to the issue itself, but instead of a "will be fixed in 3.0" label, why not just use milestones?

**Comment by tattyseal** [comment]
@elifoster Done that, thanks I forgot about them :stuck_out_tongue_winking_eye:

**Comment by tattyseal** [comment]
I think this commit will fix this issue but let me know if it doesn't, but for now I can't replicate it on that commit. https://github.com/tattyseal/CompactStorage/commit/25bf15612bb44a579c12c0f62dacc5ea0ae617f1
