### ISSUE TITLE
Rows and Columns are reversed

### ISSUE THREAD

**Issue by VortexJD** [tattyseal/IssueTracker#11]
Using 2.0.0.12 included in AgSkies2 1.1.8

In the builder, the Rows and Columns options produce the reverse of the desired result.

Columns should be vertical and Rows should be horizontal.  When I create a 3 Row x 9 Column chest, I expect a standard chest size/layout, however I get a tall chest instead of a wide one.  I think these are just reversed.

**Comment by tattyseal** [comment]
I will fix this.
