### ISSUE TITLE
Compact Chests voiding items when using Applied Energistics storage buses

### ISSUE THREAD

**Issue by awade33** [tattyseal/IssueTracker#12]
When you place an Applied Energistics storage bus any sized compact chest, once the chest fills up you can still place items into the AE terminal but it instead voids the item. I've tried with multiple sizes and even having multiple chests on a network but it will only pick one chests and once it's full it will void any other items and not move on to the next chest.

**Comment by tattyseal** [comment]
What version are you using?

**Comment by awade33** [comment]
The latest: 1.7.10-release-2.1.0-lts.15-universal

**Comment by awade33** [comment]
The lastest version on Curse: 1.7.10-release-2.1.0-lts.15-universal

**Comment by tattyseal** [comment]
Ok, thanks. I will look into it, but thinking about it, I can't see how this would be a compact storage issue but that doesn't mean its not.

**Comment by tattyseal** [comment]
I have left an issue on the Applied Energistics issues page incase it is on their end but I will look at it myself also, https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1860

**Comment by tattyseal** [comment]
Will be fixed in the next version.

**Comment by tattyseal** [comment]
Fixed in http://minecraft.curseforge.com/mc-mods/223703-compactstorage
