### ISSUE TITLE
It's possible to place a backpack within its self causing a server crash, and a lost bag

### ISSUE THREAD

**Issue by Cisien** [tattyseal/IssueTracker#13]
Crash Log:
http://pastebin.com/z4n3cTax

To reproduce:
Build a bag
Place the bag in slot 1 of the hotbar (left most slot)
open the bag
hover the mouse over an empty slot in the bag's inventory
press 1
observe the crash.

I suspect what is happening, is the game is saving the inventory, when it gets to saving the backpack that is within its self, it saves that item, which contains an inventory, containing the bag, and boom, infinite loop.

**Comment by tattyseal** [comment]
Please try this with 2.1 and report back. Don't report bugs like this without trying the latest version.

**Comment by tattyseal** [comment]
I'm going to assume here that the user tried in 2.1 and it was fixed. If not please comment and I will reopen the issue.
