### ISSUE TITLE
Voided items

### ISSUE THREAD

**Issue by Gamejet** [tattyseal/IssueTracker#14]
Chest with very low slots (I only accidently tested it with one Slot) doesnt react correctly to automated item insertion. Basicaly the chest will work fine until its full. After that it will still accept items from item insertion (such as AE2, ThermalDynamics or just Hoppers) but delete all the new incoming items.

**Comment by tattyseal** [comment]
Please follow the issue guidelines. https://github.com/tattyseal/IssueTracker/blob/master/CONTRIBUTING.md

**Comment by tattyseal** [comment]
Also, try the latest version as this exact bug was reported and if you're not using the latest version what's the point in posting an issue like this, that was posted almost a month ago and fixed within a day. If you are using the latest version repost your issue following the guidelines.
