### ISSUE TITLE
Issue: Bag Inside Itself Crash

### ISSUE THREAD

**Issue by MokahTGS** [tattyseal/IssueTracker#16]
So there is a nasty bug with the bags where shift-clicking or space-clicking on your hotbar containing the bag will crash the server.  This also destroys the bag and everything in it.

Any way to disable shift-clicking and space-clicking on the bag?

**Comment by tattyseal** [comment]
Hello,

Next time you submit an issue please follow the guidelines.

Back to this issue.

Please provide the log from the crash so this can be fixed. 

Thanks

**Comment by MokahTGS** [comment]
What's happening?: So there is a nasty bug with the bags where shift-clicking or space-clicking on your hotbar containing the bag will crash the server. This also destroys the bag and everything in it.

What's expected to happen?: Same I guess

Modpack (if applicable): Personal

Reproduction Steps: Place bag in your hotbar, open it and then shift click it or space-click any item on the hotbar into itself.
Do you have FastCraft (yes/no): Yes

Mod Version: compactstorage-1.7.10-release-2.1.0-lts.18-universal

Minecraft Version: 1.7.10
Forge Version: 10.13.4.1566
Log URL: https://dl.dropboxusercontent.com/u/9882100/Minecraft/crash-2015-12-12_22.00.33-server.txt

**Comment by tattyseal** [comment]
@MokahTGS Try without FastCraft? I know this sounds stupid but sometimes it can fix issues like this

**Comment by MokahTGS** [comment]
Is that just for bug checking?  Will you address the code issues involved with this as operating without FastCraft is not desired.

**Comment by tattyseal** [comment]
@MokahTGS Well, the issue with most FastCraft related problems is that FastCraft modifies game code so if it is to do with that then I most likely can't fix it but if it's fixable I will. And no you can't specifically disable it.

**Comment by MrPotatoGaming** [comment]
I can confirm, I don't have FastCraft. I can give you my Server Crash log, and my client log?

**Comment by tattyseal** [comment]
@MrPotatoGaming Updating should fix it..

**Comment by MrPotatoGaming** [comment]
Sorry for the miss-information, was running an old instance. And thought I was on my own issue. However, I /can/ still confirm this issue. The problem occurs with just Inventory Tweaks (v1.58-147) and Compact Storage (v2.1..0-lts.20) installed. To reproduce, open up the bag, and shift-click on the hotbar.

**Comment by tattyseal** [comment]
@MrPotatoGaming Could be an issue with inv tweaks moving items and not checking ```slot.canMoveItem()``` or similar.
