### ISSUE TITLE
Transporting Chests Erases Contents

### ISSUE THREAD

**Issue by Shykel** [tattyseal/IssueTracker#17]
Using anything that transports chests (such as Mekanism's cardboard box) erases EVERYTHING inside it and reduces it to the smallest size.

It says "you did something bad! :(" after removing the cardboard box/placing it down. if it's intentional, could you please make it configurable?

Forge/Minecraft: 1.7.10 - 10.13.4.1614 
Mod Version: compactstorage-1.7.10-release-2.1.0-lts.18-universal

Absolutely love this mod and everything about it, thank you!

**Comment by tattyseal** [comment]
Pretty sure this isn't an issue on my end but I could be wrong, also next time follow the issue guidelines. I will look into it though.

**Comment by Shykel** [comment]
Sorry about that, I posted then saw the guidelines after posting and didn't have time to post a log. It also happens with Thaumic Tinkerer's wand focus of dislocation (pretty much does the same thing at the cost of magic) but doesn't erase the contents, just posts the same message. Do you still want a log or is it too late?

**Comment by tattyseal** [comment]
It would still be helpful

**Comment by Shykel** [comment]
[fml-client-latest.txt](https://github.com/tattyseal/IssueTracker/files/67905/fml-client-latest.txt)

**Comment by tattyseal** [comment]
Please upload it to https://gist.github.com/

**Comment by Shykel** [comment]
https://gist.github.com/Shykel/f867a7a9338c47a1d536

**Comment by tattyseal** [comment]
Still not sure on this issue. I think it could be to do with the way other mods write the NBT to the stack but I don't know yet. Sorry.

**Comment by Shykel** [comment]
that's alright it's still the best and simplest storage mod out there :) there's a wand from Not Enough Wands that works perfectly with it anyway so I'll just use that for now. Best of luck with this mod!

**Comment by tattyseal** [comment]
Not applicable to 4.0 and above
