### ISSUE TITLE
Issue: Dupe bug

### ISSUE THREAD

**Issue by MrPotatoGaming** [tattyseal/IssueTracker#18]
What's happening?:  The compact storage bags are duping items inside itself. On occasion, I'll open up my backpack, and I'll see duplicates of items, they're not ghost items as I can fully interact with them.  From what I can tell, it only happens to maxSize1 stacks. Such as pickaxes and the such. Though it could be happening to normal stacks as well.
Modpack (if applicable):  Custom modpack, non-public (Heavily modified FTB Vanilla +)
Reproduction Steps: Can't really pin point how it happens.
Do you have FastCraft (yes/no): No

Mod Version: 2.1.0-lts.18
Minecraft Version: 1.7.10
Forge Version: 1558
Log URL: http://paste.ee/p/GC7jY

On a side note, I have no idea how to reproduce it. The dupe seems to be very specific because it doesn't happen very often. Nor does it happen toe very item in the bag. I ended up with 3 pickaxes, 4 axes 1 shovel and 2 swords.

**Comment by tattyseal** [comment]
Hmmm... this is a strange one, I'll look into it

**Comment by MrPotatoGaming** [comment]
When using the hotkeys to move an item to a different slot, if the hotkey you press to move an item out of the bag, is the same slot as the bag, it'll cause the bag to move into the inventory. Then, when you close out of the GUI, the bag wont save. I believe it's Project Red has a trick that stops this from happening, and it also prevents the pouch from being put inside of itself. The item becomes a red cross and can't be interacted with at all.

**Comment by tattyseal** [comment]
Try the latest version

**Comment by tattyseal** [comment]
@MrPotatoGaming Yeah the latest version is 2.1.20 and you're on 2.1.18 this bug should be fixed there, test and get back to me if you can :smile:

**Comment by MrPotatoGaming** [comment]
Wow, I'm so sorry to of wasted your time. I had so recently updated, I hadn't even thought to check if there was an update. I updated a little less than a week ago. Thank you for the support.

**Comment by tattyseal** [comment]
@MrPotatoGaming it's OK these things happen :smiley:
