### ISSUE TITLE
Bad

### ISSUE THREAD

**Issue by theoriginalbit** [tattyseal/IssueTracker#2]
This idea is bad in oh so many ways.

**Comment by tattyseal** [comment]
List some ways.

**Comment by theoriginalbit** [comment]
how about just one, a fairly important one thus making others mute in comparison; there is no link between the product and the issues, therefore there cannot be adequate assessments of quality by users, and for you you cannot close issues from a commit message.

I suppose it also stands that if your users were to find this repository somehow, chances are you'd be likely to get duplicate issues because they would potentially have to read through more issues to see if it is a duplicate, and thus they'd be less likely to do so.

in your eyes, what benefit does issue consolidation through creation of this new repository provide?
