### ISSUE TITLE
Open Anything FPS Lag

### ISSUE THREAD

**Issue by whitestarx0312** [tattyseal/IssueTracker#3]
Upon opening a builder, or any chest/bag, the FPS goes from 130 into the 20's. There is also a distinct lag spike immediately when opening. I'm not sure what causes this, but I am having the issue on Agrarian Skies 2.

Forge: forge-10.13.3.1387
CompactStorage: compactstorage-1.7.10-release-2.0.0.8-universal
Agrarian Skies 2: 1.0.39

Screens: http://imgur.com/a/GrMyr

*I am using Optifine and Fastcraft, but I don't think this is the issue.

**Comment by whitestarx0312** [comment]
(Copied from original Compact Chests issue)
@sctjkc01 sctjkc01
about 3 hours ago

Forge 10.13.3.1387; CS 1.7.10-release-2.0.0.9-universal, AgSkies 2 1.0.39 (personally updated CS outside of the pack), Fastcraft 1.21

Same issue. Running off a Surface Pro, going from 45-ish FPS to slideshow speeds in no time flat when opening either the builder or a built chest. Haven't tried a backpack yet, I'm too poor.

However, I think I know what the issue is. You're using a ninepatch implementation to dynamically draw various sizes of chest, iterating over several hundred or so times on the x and y axes, and drawing a single pixel texture (at worst) to the screen. I'm no expert at OpenGL, but I would think that trying to render (again, at worst) tens of thousands of sprites on the screen would cripple a system.

Take a page from Vanilla's book. Draw out the maximum size of chest that you need and selectively render only what's needed. Since it seems like you don't let anyone build any larger than a 24col x 12row chest, I suggest you draw that one out, and then take parts off of that to render your chest. MINIMIZE the number of sprites you're using as much as possible!

As far as the Chest Builder goes, I don't see why you're doing the same thing. That GUI doesn't change size (unless I'm missing something dumb) so there's no need to use any ninepatch-hack stuff. Draw out your GUI ahead of time and just drop it whole into the screen.

Everyone's computers shall thank you.

**Comment by tattyseal** [comment]
The reason for this happening with chests is due to the fact I allow map makers to specify size with a command. Show me screens from a chest not the builder as the builder is getting fixed. I was meant to before release.

**Comment by sctjkc01** [comment]
> [...]I allow map makers to specify size with a command.

The code that you have doesn't allow for that, from what I can see.  Between [limiting the chest sizes in the builder to hardcoded values](https://github.com/tattyseal/CompactStorage/blob/2.0/src/main/java/com/workshop/compactstorage/client/gui/GuiChestBuilder.java#L310) and [not having any in-game command to change maximum chest sizes] (https://github.com/tattyseal/CompactStorage/blob/2.0/src/main/java/com/workshop/compactstorage/command/CommandCompactStorage.java#L43) I don't see any reason why you'd need to nine-patch the chest GUI.

If that's meant to be a future thing, then by all means ignore the above.

**Comment by whitestarx0312** [comment]
http://imgur.com/RE7Syr1
http://imgur.com/ePGgyJX

Same thing is happening with chests.

**Comment by sctjkc01** [comment]
I'd like to add in another two cents about optimizing the chest GUIs:

You've got an absurd amount of overlap when rendering.  You [render every pixel of the background](https://github.com/tattyseal/CompactStorage/blob/2.0/src/main/java/com/workshop/compactstorage/client/gui/GuiChest.java#L86) then [completely overwrite it with the slot backgrounds](https://github.com/tattyseal/CompactStorage/blob/2.0/src/main/java/com/workshop/compactstorage/client/gui/GuiChest.java#L97).  If you're dead set on sticking with the ninepatch hack, I highly suggest you skip over any pixels that are behind the slots at the bare minimum to ease the strain on the GPU.

**Comment by VictiniX888** [comment]
@tattyseal I'm using 3.0 latest, seems to be fixed for chest and backpack, but builder is still lagging

**Comment by tattyseal** [comment]
Fixed for the chests and will be fixed by the builder overhaul in 3.0. This will not be fixed in 2.0 as it required a whole GUI overhaul.
