### ISSUE TITLE
Transposition sigil from sanguimancy deletes contents of compact chests.

### ISSUE THREAD

**Issue by NolanSyKinsley** [tattyseal/IssueTracker#4]
I have posted this to both mods, as I don't know which one is causing it exactly. The teleposition sigil, which acts like a dolly or cardboard box from mekanism, is resetting compact chests when moved, and issuing the "You attempted to do something bad :(" message, deleting the entire contents of the chests.

No other mods that move blocks trigger it, but the sanguimancy transposition sigil does.

**Comment by tattyseal** [comment]
Please post logs.

**Comment by tattyseal** [comment]
"You must include logs. They can be found here: ``logs/fml-client-latest.log`` or ``logs/fml-server-latest.log`` in your Minecraft directory. Please use http://paste.minecraftforge.net to post logs as they are too long for Github issues."

**Comment by tattyseal** [comment]
Not updated in over 2 months.
