### ISSUE TITLE
Sorry please apologies my finger =="

### ISSUE THREAD

**Issue by PlayOnly** [tattyseal/IssueTracker#7]
Crasher Report: https://gist.github.com/anonymous/204ef1c62eaf29a05395

Dunno wether is the same problem issued by mallrat...

Situation: Let say compactstorage backpack is in slot bar 4, while opening that backpack...then I accidently hit number 4... which cause that backpack to be stored in its own inventory... then boom crash...
Also, backpack chest sound... can we have no sfx?

Thank you for your hard work...

**Comment by tattyseal** [comment]
The backpack sfx is programmed there for a reason...

This bug will be fixed when I can.
