### ISSUE TITLE
Chest & Backpack GUI bug (CompactStorage 3.0)

### ISSUE THREAD

**Issue by VictiniX888** [tattyseal/IssueTracker#8]
![2015-07-17_14 56 49](https://cloud.githubusercontent.com/assets/9777462/8742158/00c063ba-2c95-11e5-9837-865f30c85163.png)
- GUI lacks a frame
- The inventory is actually centered, not left-aligned, causing items in inventory to appear on the lines

**Comment by tattyseal** [comment]
Meant to be like that look at commits pls :P

**Comment by VictiniX888** [comment]
At least fix the inventory...

**Comment by tattyseal** [comment]
It is "alpha" for a reason. pls.
